### ISSUE TITLE
Enable/Disable plot by clicking in the index & Optimisation Addpoint

### ISSUE THREAD

**Issue by GourmelenGuillaume** [BenjaminNavarro/rtplot#1]
Enable/Disable plot by clicking in the index
Optimisation Addpoint uses lists to find min and max on every point in the case Auto Range would be active. In case autoRange is not used we would want not wasting time to classify every point in a list

**Comment by BenjaminNavarro** [comment]
Implemented with `rtplot-core` v0.3.0 and `rtplot-fltk` v1.2.0
